# PostgreSQL Client Authentication Configuration File for Replica
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# Allow connections from Docker network
host    all             all             172.16.0.0/12           trust
host    all             all             192.168.0.0/16          trust
host    all             all             10.0.0.0/8              trust

# Allow connections from app server
host    all             all             217.60.36.94/32          scram-sha-256
host    myapp_db        new_cheburashka_2004      217.60.36.94/32          scram-sha-256

# Allow connections from master server (including PgBouncer)
host    all             all             31.57.62.46/32        scram-sha-256
host    myapp_db        new_cheburashka_2004      31.57.62.46/32        scram-sha-256